version: "3"
services:
  activemq:
    container_name: activemq
    image: islandora/activemq:2
    environment:
      - ACTIVEMQ_USER=admin
      - ACTIVEMQ_PASSWORD=password
      - ACTIVEMQ_WEB_ADMIN_NAME=admin
      - ACTIVEMQ_WEB_ADMIN_PASSWORD=password
      - ACTIVEMQ_WEB_ADMIN_ROLES=admin
    ports:
      - "8161:8161"
      - "61616:61616"

  database:
    container_name: db-mysql
    restart: always
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: archive

  my-app:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - activemq
      - database
